required:
  type:
    type: string
    allowed-values:
      - global-config-item-values
  global-config-item-values:
    type: list
    element-type: global-config-item-value

definitions:
  global-config-item-value:
    required:
      name:
        type: string
      value:
        type: any
      is_value_templated_string:
        type: bool
        default: false
    optional:
      value_true_type: # only used in the IDE
        type: string
      prefix:
        type: string