%auto_generated_file_disclaimer%

global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# A scrape configuration containing qorus:
scrape_configs:
  - job_name: "qorus"
    scrape_interval: 60s
    metrics_path: "/api/metrics"
    scheme: %qorus_scheme%
    tls_config:
        insecure_skip_verify: true
    static_configs:
    - targets: ['%qorus_endpoint%']
