{
 "title": "Test",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "band", "query": "qorus_order_stats_sla" },
   {
    "name": "node_name",
    "query": "qorus_cluster_info_node_load_pct"
   },
   { "name": "workflow_id" }
  ]
 },
 "panels": [
  {
   "title": "SLA Stats",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "qorus_order_stats_sla{band=\"$band\",in_sla=\"1\"}",
     "legendFormat": "in SLA"
    },
    {
     "expr": "qorus_order_stats_sla{band=\"$band\",in_sla=\"0\"}",
     "legendFormat": "out of SLA"
    }
   ]
  },
  {
   "title": "Workflow Disposition",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "qorus_order_stats_disposition{disposition=\"C\",band=\"$band\"}",
     "legendFormat": "Completed w/o errors"
    },
    {
     "expr": "qorus_order_stats_disposition{disposition=\"A\",band=\"$band\"}",
     "legendFormat": "Recovered Automatically"
    },
    {
     "expr": "qorus_order_stats_disposition{disposition=\"M\",band=\"$band\"}",
     "legendFormat": "Recovered Manually"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"C\"}",
     "legendFormat": "COMPLETE"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"Y\"}",
     "legendFormat": "READY"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"S\"}",
     "legendFormat": "SCHEDULED"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"N\"}",
     "legendFormat": "INCOMPLETE"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"V\"}",
     "legendFormat": "EVENT-WAITING"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"A\"}",
     "legendFormat": "ASYNC-WAITING"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"W\"}",
     "legendFormat": "WAITING"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"R\"}",
     "legendFormat": "RETRY"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"E\"}",
     "legendFormat": "ERROR"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"I\"}",
     "legendFormat": "IN-PROGRESS"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"X\"}",
     "legendFormat": "CANCELED"
    },
    {
     "expr": "qorus_actual_workflow_instances_statuses{id=\"$id\",status=\"B\"}",
     "legendFormat": "BLOCKED"
    }
   ]
  },
  {
   "title": "Node CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "qorus_cluster_info_node_load_pct{node_name=\"$node_name\"}",
     "legendFormat": "CPU load"
    }
   ]
  },
  {
   "title": "Node Memory Progression",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "qorus_cluster_info_node_ram{node_name=\"$node_name\"}",
     "legendFormat": "Total {{node_name}} RAM"
    },
    {
     "expr": "qorus_cluster_info_node_ram_in_use{node_name=\"$node_name\"}",
     "legendFormat": "Total RAM used"
    },
    {
     "expr": "qorus_cluster_info_node_priv{node_name=\"$node_name\"}",
     "legendFormat": "RAM used by Qorus"
    }
   ]
  },
  {
   "title": "Number of Services",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "qorus_service_total", "legendFormat": "Total" },
    { "expr": "qorus_service_alerts", "legendFormat": "Alerts" }
   ]
  },
  {
   "title": "Node Process Count History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qorus_cluster_info_process_count{node_name=\"$node_name\"}",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "qorus_job_total", "legendFormat": "Total" },
    { "expr": "qorus_job_alerts", "legendFormat": "Alerts" }
   ]
  },
  {
   "title": "Number of Workflows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "qorus_workflow_total", "legendFormat": "Total" },
    { "expr": "qorus_workflow_alerts", "legendFormat": "Alerts" }
   ]
  },
  {
   "title": "Workflow Overall Statuses",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"C\"}",
     "legendFormat": "COMPLETE"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"Y\"}",
     "legendFormat": "READY"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"S\"}",
     "legendFormat": "SCHEDULED"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"N\"}",
     "legendFormat": "INCOMPLETE"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"V\"}",
     "legendFormat": "EVENT-WAITING"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"A\"}",
     "legendFormat": "ASYNC-WAITING"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"W\"}",
     "legendFormat": "WAITING"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"R\"}",
     "legendFormat": "RETRY"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"E\"}",
     "legendFormat": "ERROR"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"I\"}",
     "legendFormat": "IN-PROGRESS"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"X\"}",
     "legendFormat": "CANCELED"
    },
    {
     "expr": "qorus_actual_workflow_overall_statuses{status=\"B\"}",
     "legendFormat": "BLOCKED"
    }
   ]
  }
 ]
}